language: node_js
node_js:
- '0.11'
- '0.10'
notifications:
  slack:
    secure: OcwvuAmXmMnwY8WWEwNgWDxHo63m+JSlUpZKJxMWsvf0KdZ/1iJ0YzpWeDRuXHI/taTME/lad6I+Eb2Nha2j3iutdjyMnvqYq0jmJA9sRiW8XhshitWyY8/SkMW37lWQ8Lgl5jfBbZrsyQ+Q0cWgDp2hFx1SfwYvVfAfpn7ZY1P81xdfUePyN1AHaEztNhVbGoA0q4rcPw0KK0Z7pY/sQZcbB/1QCQNnqr6SReG7xj2+/byhHIf8xUleSwMDbG7JhjcNITwm6Ga8NNMI28Vz0n0u5GOFA1BkE1J6S/DtnXRHI5MsovHx7f5w1uFKAAaahyMuoszDN+bDaiMDM5EKc6gARlnacwkcn/vvDJREucIf2ec5MJuM4ITNlOzctIQnXxc2+KlM89T7FV2VGrwcQlV4vegMsf/bPlh8zVVb+q9PcJnCr7VwTTO7jamCQiSUmsOnNcE6UHdduSAJESnmOqBkjBRqkW0wI3DhF4ewVL0zJs3qzL3jKK4lupeL9XOe+h13SgFhF10GUQytFZ9SPpD9yPflQdVMrwF3dqdldhktEFngI+tRulUMRafKToGKPuT9NSyjySUxO9bdKjrjyOMP9zNnWYxnCIdfWqKkuOx+ZPrEzf97POSZ5uKJzG3RVODX/Q2Dk/mb/2QcwOvMFgCKPSBZ2LWpqhYWklxvl8U=
